### ISSUE TITLE
Add possibility to ignore particular nuget packages

### ISSUE THREAD

**Issue by kevtk** [blackducksoftware/nuget-dotnet3-inspector#3]
Hi folks,

we often have the issue that we can't exclude single NuGet packages.
We see a lot of NuGet packages that are not relevant at all (e.g. for internal build tasks, scripting libraries etc.).

The excluded-modules command can only extract e.g. C# projects, am I right?

Easiest way to implement that is an ignore file or one more argument in the same manner like with the exclude modules argument.
A simple private RegEx Match method to prevent single NuGet packages to be added to the collection would be enough I think. 

Kind Regards
Kevin

**Comment by stevebillings** [comment]
Please route your request through Synopsys technical support.
